apiVersion: apps/v1
kind: Deployment
metadata:
  name: bogay-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bogay-express
  template:
    metadata:
      labels:
        app: bogay-express
    spec:
      containers:
        - name: bogay-express
          image: bogay-express:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
